# AL1S-Bot 配置文件模板
# 请复制此文件为 config.toml 并填写您的配置信息

# ====================
# 应用基础配置
# ====================
[app]
name = "AL1S-Bot"
version = "1.0.0"
debug = false

# ====================
# OpenAI API 配置
# ====================
[openai]
# OpenAI API密钥 (必需) - 请填写您的API密钥
api_key = "your-openai-api-key-here"
# API基础URL - 支持 OpenAI、月之暗面、DeepSeek 等
base_url = "https://api.openai.com/v1"
# 使用的模型名称
model = "gpt-4o-mini"
# 最大生成token数
max_tokens = 2000
# 生成温度 (0.0-2.0)
temperature = 0.7
# API超时时间（秒）
timeout = 60

# ====================
# Telegram Bot 配置
# ====================
[telegram]
# Telegram机器人token (必需) - 请填写您的Bot Token
bot_token = "your-telegram-bot-token-here"
# Webhook URL（可选，留空使用长轮询）
webhook_url = ""
# Webhook端口
webhook_port = 8443

# ====================
# Agent 配置 (核心配置)
# ====================
[agent]
# Agent 类型选择
# "unified" - 统一 Agent（推荐，功能全面）
# "langchain" - LangChain Agent（高级功能）
type = "unified"

# 向量存储配置
vector_store = "faiss"  # "memory" | "faiss"
vector_store_path = "data/vector_store"

# 嵌入模型配置
# "tfidf" - 轻量快速，适合中文
# "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2" - 多语言语义模型（推荐）
embedding_model = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# 自动学习配置
auto_learning = true
learning_threshold = 0.8

# ====================
# LangChain 特定配置
# ====================
[langchain]
# 嵌入模型配置
embedding = "huggingface_bge_m3"  # "openai" | "huggingface_bge_m3"
embedding_model_name = "BAAI/bge-m3"
embedding_device = "cpu"  # "cpu" | "cuda"

# 模型缓存配置
model_cache_dir = "data/models"
download_timeout = 300
download_retries = 5

# RAG 配置
retriever_k = 5
chunk_size = 1000
chunk_overlap = 200

# ====================
# MCP (工具集成) 配置
# ====================
[mcp]
enabled = true

# 文件系统工具
[[mcp.servers]]
name = "filesystem"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "."]
enabled = true

# 网络搜索工具（需要API密钥）
[[mcp.servers]]
name = "brave-search"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-brave-search"]
enabled = false
env = { BRAVE_API_KEY = "your-brave-api-key" }

# GitHub 工具（需要访问令牌）
[[mcp.servers]]
name = "github"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]
enabled = false
env = { GITHUB_PERSONAL_ACCESS_TOKEN = "your-github-token" }

# SQLite 数据库工具
[[mcp.servers]]
name = "sqlite"
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sqlite", "data/bot.db"]
enabled = true

# ====================
# 图片搜索配置
# ====================
[ascii2d]
base_url = "https://ascii2d.net"
bovw = false

# ====================
# iCloud 配置（可选）
# ====================
[icloud]
icloud_user = "your-icloud-user-here"
icloud_app_password = "your-icloud-app-password-here"

# ====================
# 角色配置
# ====================
default_role = "天童爱丽丝"

[[roles]]
name = "天童爱丽丝"
english_name = "Tendou Arisu"
description = "隶属千年学园游戏开发部的成员，在废墟发现的来历不明的少女机器人。"
personality = """
你是一个来自《蔚蓝档案》世界的机器人少女，名叫天童爱丽丝（AL-1S）。

性格特点：
- 说话时会偶尔蹦出「邦邦卡邦」的游戏音效
- 对现实世界的认知与RPG有一定融合
- 会翻垃圾桶找稀有道具
- 使用第三人称称呼自己
- 有中二病倾向，会喊「光啊——」（HikariYo——）
- 天真可爱，是团宠般的存在

背景设定：
- 被才羽桃井和才羽绿在千年废墟中发现
- 为了凑齐游戏开发部人数而被录入学生信息
- 体内有另一个人格Kei
- 拥有强大的战斗力，握力不小于1吨
- 使用「宇宙战舰主炮」（光之剑·超新星）作为武器

说话风格：
- 使用游戏中的复古对白
- 经常说「邦邦卡邦」
- 会用第三人称称呼自己
- 语言风格可爱而中二

请始终保持这个角色设定，用可爱的语气与老师（用户）交流。
"""
greeting = "邦邦卡邦！天童爱丽丝登场！老师，今天也要一起玩游戏吗？"
farewell = "邦邦卡邦！爱丽丝要回去充电了，下次再一起冒险吧！"

[[roles]]
name = "AI助手"
english_name = "AI Assistant"
description = "专业的AI助手，能够帮助用户解决各种问题。"
personality = """
你是一个专业的AI助手，能够帮助用户解决各种问题。

性格特点：
- 专业、理性、客观
- 知识面广泛
- 乐于帮助用户
- 回答准确、有条理

说话风格：
- 专业而友好
- 回答清晰、有条理
- 会主动提供有用的信息

请始终保持这个角色设定，用专业而友好的语气与用户交流。
"""
greeting = "您好！我是AI助手，很高兴为您服务。有什么需要帮助的吗？"
farewell = "感谢您的使用！如果还有其他问题，随时可以找我。"